### ISSUE TITLE
[networking]  ngrx-ducks library

### ISSUE THREAD

**Issue by GregOnNet** [michaeljota/ngrx-ducks#4]
Hi @michaeljota,

thank you for providing this guide.
I came across your work due my work on a similar solutions bringing the ducks pattern to ngrx.

You can see the result at https://github.com/co-IT/co-it/tree/master/ngrx/ducks.

I am excited about your feedback since you also care about this topic.

**ngrx-ducks**
- ⚙️ Create Reducer Automatically
- 🤫 Get rid of verbose action declarations
-️️️ ⤵️ Reduce imports of Action Types and Action Creators
- 💉 Use typed Services instead of dispatching Actions
- 🙅‍ No code generation that needs ot be maintained manually

Thanks in advance
Gregor

**Comment by michaeljota** [comment]
Hi @GregOnNet 

Thank you for your interest in my guide. I looked into your library. Good approach to reduce boilerplate code. I will test it to see how it handle type safe, and understand the workflow better.

What do you think about this guide? I wanted to do a guide to get the best from rxjs, Angular, Typescript and ngrx. I know I missing some points, but I would like some feedback about this.

**Comment by GregOnNet** [comment]
First of all, thank you for providing that guidance. I am sure it took quite a bit of time to write everything down.

Sure, I am glad to share my thoughts with you:

### Extension Style 03-03

To initialize the default state with a class may not be needed since you can create the default state by using **ngrx/entity** `adapter.getInitialState()`.

### Extension Style 04-06

I really like that you group everything into directories.
Maybe you want to mention that this can be achieved by using the `--group` parameter of **ngrx/schematics**

I do not get the idea why you want to create reducers per container components.
From my experience, there is indeed a correlation but it is not a 1:1 mapping.
That's why I would not enforce it by a rule.

### Extension Style 04-09

Thank you 🙏, for pointing this out.
I believe `StoreModule.forFeature` is not very well known, but it should.
> This is just my personal perspective.

### Extension Style 05-15

I disagree with this style.
The only service a Component has to know is the Store.
This is the piece of cake you can get from introducing Redux.
Just inject the store and get the projected data you need using `selectors`.

I fear that you run into a Component-Store/Service micromanagement that potentially leads into service composition again.

> **Again** This is my personal opinion. Please take this as friendly feedback. I am open to your arguments. :)

### Style NGRX-01

I believe this is also the way the ngrx team goes.
If you have a look at  https://github.com/co-IT/co-it/tree/master/ngrx/ducks you will see that you achieve this with less explicit configuration.

### Style NGRX-02

Same here. I do not want to create yet another service that needs to be maintained.
I do this automatically using  https://github.com/co-IT/co-it/tree/master/ngrx/ducks.

### Style NGRX-05

This is an interesting one.
I also look for a better way to organize `selectors` instead of placing them in to `index.ts` barrel files.
Thoms Burleson introduced the term of a Facade that provides selectors and action creators: https://medium.com/@thomasburleson_11450/ngrx-facades-better-state-management-82a04b9a1e39

### Style NGRX-06

👍 for Barrel Files.
You may need to add a hint as well that barrel files are a bit dangerous as well.
Never reference a barrel to another barrel to avoid cyclic imports.

I hope that I was able to provide some valuable input.

**Comment by michaeljota** [comment]
Thanks you. Just a couple of notes. :P. 

> #### Extension Style 03-03
> To initialize the default state with a class may not be needed since you can create the default state by using ngrx/entity adapter.getInitialState().

Actually, `getInitialState()`  does not have notion of anything else outside the entity, meaning that it only will create an object like `ids: [], entities: {}`. If you have any additional properties, or creating an initial state for your entities, you won't have then available. 

> #### Extension Style 05-15
> I disagree with this style.
The only service a Component has to know is the Store.
This is the piece of cake you can get from introducing Redux.
Just inject the store and get the projected data you need using selectors.
> 
> I fear that you run into a Component-Store/Service micromanagement that potentially leads into service composition again.
> 
> > Again This is my personal opinion. Please take this as friendly feedback. I am open to your arguments. :)

I maybe misunderstood. I'll try to update that part and make this points more clear as I really wanted to mean what you said. Your component should only be provided with the store service, and this have to provide all the data your component needs. 

> I do not get the idea why you want to create reducers per container components. From my experience, there is indeed a correlation but it is not a 1:1 mapping.

I think this helps to organize better, and as you said, there is always a correlation. Most the time, you can do a 1:1 mapping, and other things outside that component can be placed in a Shared module.

**Comment by michaeljota** [comment]
I'm really thankful for your feedback. I'll read more about facades, as it seems to be a good approach to organize the store ducks and be able to reduce the components at the same time.

**Comment by GregOnNet** [comment]
The Library NgRx Ducks has improved even more.
If you are interested, I always look for feedback: https://co-it.gitbook.io/ngrx-ducks/

Closing this ticket.
